//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKR_TRAVELS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus_View
    {
        public int Bus_ID { get; set; }
        public string BoardingPoint { get; set; }
    }
}
