//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKR_TRAVELS_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using PKR_TRAVELS_DB;
    
    public partial class MYBUSEntities1 : DbContext
    {
        public MYBUSEntities1()
            : base("name=MYBUSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
        public virtual DbSet<Bus_View> Bus_View { get; set; }
    
        public virtual ObjectResult<spMyBusInfo_Result> spMyBusInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMyBusInfo_Result>("spMyBusInfo");
        }
    }
}
